baseURL: https://normes.transport.data.gouv.fr
languageCode: fr
title: Normes des données de transport
theme: "PaperMod"

defaultContentLanguage: 'fr'
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    fr:
        languageName: "French"
        weight: 1
        menu:
            main:
                # - name: Recherche
                #   url: search/
                #   weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

    # fr:
    #     languageName: ":fr:"
    #     languageAltTitle: French
    #     weight: 2
    #     title: PaperModL2
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         # imageUrl: "#"
    #         # imageTitle: my image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Tags
    #               url: tags
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: Tags
    #               url: tags
    #               weight: 10
    #             - name: Categories
    #               url: categories
    #               weight: 10
    #             - name: Series
    #               url: series
    #               weight: 10
    #             - name: NullLink
    #               url: "#"
    #             - name: NullLink2
    #               url: "#"
    #             - name: NullLink3
    #               url: "#"

    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     menu:
    #         main:
    #             - name: Tags
    #               url: tags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON
ignoreFiles:
  - README\.md$

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description:
    author:
    # author: ["Me", "You"] # multiple authors


    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: true
    ShareButtons:
        - twitter
        - linkedin
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    applause: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Normes de transport en commun"
        Content: |
            ## Contexte
            L'ouverture données statiques, dynamiques, observées et historiques des déplacements multimodaux est encadrée :
            - au niveau européen, par le [règlement délégué (UE) 2017/1926](https://eur-lex.europa.eu/eli/reg_del/2017/1926/2024-03-04) de la Commission du 31 mai 2017 modifié par le règlement délégué (UE) 2024/490 de la Commission du 29 novembre 2023, dit "règlement MMTIS". Ce règlement complète la directive 2010/40/UE du Parlement européen et du Conseil en ce qui concerne la mise à disposition, dans l'ensemble de l'Union, de services d'informations sur les déplacements multimodaux.
            - au niveau français, par les articles L. 1115-1 à L. 1115-7, D. 1115-1, R. 1115-2 à R. 1115-8 et D. 1115-9 à D. 1115-11 du code du transports, notamment créés ou modifiés par la loi n° 2019-1428 du 24 décembre 2019 d’orientation des mobilités, dites loi "LOM".

            D'une part, les données existantes doivent être mises à disposition sur le point d’accès national des données multimodales en utilisant notamment les normes et spécifications techniques suivantes :
            - Pour les données routières : le format défini par le règlement dit "RTTI" ;
            - Pour les autres données :
                - NeTEx CEN/TS 16614 et ses versions ultérieures, dit "NeTEx" ;
                - SIRI CEN/TS 15531 et versions ultérieures, dit "SIRI" ;
                - La norme établissant le modèle de données de référence pour le Transport Public Transmodel EN 12896 en l’absence de protocole d’échange de référence.

            D’autre part, les profils nationaux correspondent à des sous-ensembles de ces normes répondant aux besoins métiers. La mise à disposition des données selon une norme respecte a minima ces profils.
            Conformément à l’arrêté du [4 mars 2022](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000045382208), les profils référencés ci-dessous correspondent aux versions officielles et en vigueur des profils à employer en France. 
            
            ## Descriptif
            Les liens ci-dessous permettent d'accéder au format web au contenu des profils. Sur chacune des pages, il sera prochainement possible de télécharger une version pdf du document correspondant. Un espace [Github](https://github.com/etalab/transport-normes), hébergeant le contenu de ces documents, offre par ailleurs la possibilité d'explorer et d'exploiter leur contenu au format markdown.

            ## Gouvernance
            Les spécifications techniques sont élaborées et maintenues par le groupe de travail GT7 relatif à l'information voyageur (AFNOR BNTRA/CN03/GT7). Des commentaires peuvent toutefois être formulés sur les pages web de chaque profil, ainsi que directement sur [l'espace de commentaires Github](https://github.com/etalab/transport-normes/issues), permettant à la communauté de producteurs et de réutilisateurs de données de remonter des informations au groupe de travail.
    socialIcons:
        - name: github
          url: "https://github.com/etalab/transport-normes"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: 'https://github.com/etalab/transport-normes/tree/main'
        Text: 'Proposer une modification' # edit text
        appendFilePath: true # to append file path to Edit link

    label:
        text: 'Normes de transport en commun'
        icon: '/logo.png'
        iconHeight: 80

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
